#!/usr/bin/env python3
"""
api-diff: track changes to vendor API documentation pages.

reads sources.toml, fetches each URL, extracts the main content, normalizes
it to markdown, and writes to docs/<path>.md. the git history of that file
becomes the changelog for that documentation page.

we deliberately don't attempt js rendering yet — pages that rely on client-side
hydration will emit a warning and be skipped. that's fine, we add playwright
support later if/when we want ambitious sources.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

try:
    import tomllib  # python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore  # fallback for 3.10 and below
from datetime import datetime, timezone
from pathlib import Path

# third-party
from bs4 import BeautifulSoup  # pip install beautifulsoup4
from markdownify import markdownify as html_to_md  # pip install markdownify

USER_AGENT = (
    "api-diff-bot (documentation change tracker; "
    "+https://github.com/0xHalo22/api-diff)"
)

ROOT = Path(__file__).resolve().parents[1]
SOURCES_FILE = ROOT / "sources.toml"
DOCS_DIR = ROOT / "docs"

# if the extracted markdown is shorter than this, assume js rendering failed
MIN_CONTENT_LEN = 400

# optional fallback selectors, tried in order if the explicit selector misses
FALLBACK_SELECTORS = ["main", "article", "[role=main]", "body"]


def fetch_html(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": USER_AGENT,
            "Accept": "text/html,application/xhtml+xml",
            "Accept-Language": "en-US,en;q=0.9",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        encoding = r.headers.get_content_charset() or "utf-8"
        return r.read().decode(encoding, errors="replace")


def extract_content(html: str, selector: str | None) -> str | None:
    soup = BeautifulSoup(html, "html.parser")

    # remove obvious noise
    for tag in soup(["script", "style", "noscript", "svg", "nav", "footer"]):
        tag.decompose()

    tried = []
    if selector:
        tried.append(selector)
    for s in FALLBACK_SELECTORS:
        if s not in tried:
            tried.append(s)

    for s in tried:
        try:
            node = soup.select_one(s)
        except Exception:
            continue
        if node is not None and node.get_text(strip=True):
            return str(node)
    return None


def normalize(md: str) -> str:
    # collapse runs of whitespace, trim trailing space on lines
    md = re.sub(r"[ \t]+\n", "\n", md)
    md = re.sub(r"\n{3,}", "\n\n", md)
    md = md.strip() + "\n"
    return md


def scrape_source(src: dict) -> tuple[str, str | None]:
    """
    returns (status, content).
      status in {'ok', 'empty', 'http-error', 'network-error'}
      content is the normalized markdown, or None on failure.
    """
    url = src["url"]
    selector = src.get("selector")

    if src.get("wait_js"):
        print(f"  [skip] js rendering required, not yet supported")
        return ("skip", None)

    try:
        html = fetch_html(url)
    except urllib.error.HTTPError as e:
        print(f"  [http-error] {e.code} {e.reason}")
        return ("http-error", None)
    except Exception as e:
        print(f"  [network-error] {e}")
        return ("network-error", None)

    content_html = extract_content(html, selector)
    if content_html is None:
        print(f"  [empty] no content extracted")
        return ("empty", None)

    md = html_to_md(
        content_html,
        heading_style="ATX",
        bullets="-",
        strip=["a:has(img)"],  # drop purely-image links
    )
    md = normalize(md)

    if len(md) < MIN_CONTENT_LEN:
        print(f"  [empty] extracted content too short ({len(md)} chars) — likely js-rendered")
        return ("empty", None)

    return ("ok", md)


def file_header(src: dict) -> str:
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return (
        f"<!--\n"
        f"source: {src['url']}\n"
        f"name: {src['name']}\n"
        f"last-fetched: {stamp}\n"
        f"this file is auto-generated by api-diff. do not edit manually.\n"
        f"-->\n\n"
    )


def run_git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def main() -> int:
    if not SOURCES_FILE.exists():
        print(f"[api-diff] no sources.toml found at {SOURCES_FILE}")
        return 1

    config = tomllib.loads(SOURCES_FILE.read_text())
    sources = config.get("source", [])
    if not sources:
        print("[api-diff] sources.toml has no [[source]] blocks")
        return 0

    print(f"[api-diff] scraping {len(sources)} sources")

    results = {"ok": [], "empty": [], "http-error": [], "network-error": [], "skip": []}
    changed_paths = []

    for src in sources:
        name = src["name"]
        path = src["path"]
        print(f"\n[{path}] {name}")
        status, md = scrape_source(src)
        results[status].append(name)
        if status != "ok" or md is None:
            continue

        out_path = DOCS_DIR / f"{path}.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        new_content = file_header(src) + md

        # compare against existing file, ignoring the last-fetched timestamp
        # so we only commit when the actual content changed
        if out_path.exists():
            old = out_path.read_text()
            old_body = re.sub(r"last-fetched: [^\n]+\n", "", old)
            new_body = re.sub(r"last-fetched: [^\n]+\n", "", new_content)
            if old_body == new_body:
                print(f"  [unchanged] no content change")
                continue

        out_path.write_text(new_content, encoding="utf-8")
        changed_paths.append(out_path)
        print(f"  [updated] wrote {out_path.relative_to(ROOT)} ({len(md)} chars)")

    # summary
    print()
    print("[api-diff] summary:")
    for status, names in results.items():
        if names:
            print(f"  {status}: {len(names)}")
            for n in names:
                print(f"    - {n}")

    if os.environ.get("GITHUB_ACTIONS"):
        if not changed_paths:
            print("[api-diff] no content changes to commit")
            return 0
        for p in changed_paths:
            run_git("add", str(p))
        status = subprocess.run(
            ["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True
        )
        if not status.stdout.strip():
            print("[api-diff] nothing to commit")
            return 0
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        msg = f"update {today}: {len(changed_paths)} page(s) changed"
        run_git("commit", "-m", msg)
        print(f"[api-diff] committed: {msg}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
